### ISSUE TITLE
question(esm): Why does Majinbuu comes from unpkg.com by default ?

### ISSUE THREAD

**Issue by douglasduteil** [WebReflection/hyperhtml-majinbuu#2]
Can you explain why you prefer to get [majinbuu from unpkg.com by default](https://github.com/WebReflection/hyperhtml-majinbuu/blob/01a6d9286e40c38a4a2197b68963515ae34fc520/esm/index.js#L3) ?

**Comment by WebReflection** [comment]
it's a browser module, and for debugging purpose, I can **test** it directly via browsers without needing any intermediate layer.

Consumer can either use the [rollup-plugin-alias](https://github.com/rollup/rollup-plugin-alias) or the recently published [rollup-plugin-cdn](https://github.com/WebReflection/rollup-plugin-cdn).

Usually, developers need tools to consume ESM packages, in this case they don't need tools to test on the main target: the browser.

However, the package is bundled as CJS without remote unpkg dependency.

There was a long [discussion yesterday on twitter](https://twitter.com/mjackson/status/933741394493038592) too about this.

Have I answered your question?
